spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/auth/jwks
          issuer-uri: http://localhost:9090/auth

server:
  servlet:
    context-path: /resource/jwt
  port: 8085

logging:
  level:
    org:
      springframework:
        security: trace
